### ISSUE TITLE
No implementation of method :init for class JWT

### ISSUE THREAD

**Issue by alexkalderimis** [liquidz/clj-jwt#12]
I admit this is bizarre, but I tried to update to 0.0.12 and got following error on a call to `(jwt claims)`:

```
java.lang.IllegalArgumentException: No implementation of method: :init of protocol: #'clj-jwt.core/JsonWebToken found for class: clj_jwt.core.JWT
          core_deftype.clj:544 clojure.core/-cache-protocol-fn
                   core.clj:22 clj-jwt.core/eval3008[fn]
                   core.clj:82 clj-jwt.core/jwt
```

I tested this on the repl with 0.0.12 and 0.0.11 before dropping back to 0.0.6, where it works. I'm rather confused by this, since you clearly implement the protocol in your code. So if you know what the problem is, I'd be glad to know and then close this issue.

**Comment by liquidz** [comment]
Could you give me sample codes that I can get the error?

**Comment by alexkalderimis** [comment]
I just whipped up a minimal code sample to replicate the error and I couldn't - this clearly has nothing to do with you; I suspect it is related to bad code being cached, which I managed to fix by doing a `lein clean`. Sorry to bother
