### ISSUE TITLE
decode HMAC256 signed token

### ISSUE THREAD

**Issue by ioRekz** [liquidz/clj-jwt#17]
Hi, I think I'm missing something important because I don't understand how I can decode my signed token without the secret.
(-> token str->jwt :claims :iss)

I always need to verify first ?

**Comment by liquidz** [comment]
@ioRekz  You can decode token without `verify`, but you should verify it to review the token is yours or not.

```clj
user=> (def claim {:foo "bar"})
#'user/claim
user=> (-> claim jwt (sign :HS256 "secret") to-str)
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIifQ.dtxWM6MIcgoeMgH87tGvsNDY6cHWL6MGW4LeYvnm1JA"
user=> (-> *1 str->jwt :claims)
{:foo "bar"}
```

**Comment by ioRekz** [comment]
ok thx !
